-- DEPRECATED: This trigger is no longer used.
-- Profile creation is now handled by the app-level auth.signUp() action.
-- The trigger was used to automatically create profiles when users signed up via Supabase Auth,
-- but since the app now manages authentication with Prisma and JWT tokens, this is no longer needed.
--
-- Previous code (archived for reference):
-- create or replace function public.handle_new_user() returns trigger as $$
-- begin
--   insert into public.profiles (id, email, role, active)
--   values (new.id, new.email, 'client', true);
--   return new;
-- end;
-- $$ language plpgsql security definer set search_path = public;
--
-- create trigger on_auth_user_created
--   after insert on auth.users
--   for each row execute procedure public.handle_new_user();
